name: passion_academia
description: A new Flutter project for Passion Academia.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^8.0.0
  http: ^1.2.0
  provider: ^6.1.2
  intl: ^0.20.2
  supabase_flutter: ^2.4.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.0
  image_cropper: ^7.1.0
  google_sign_in: ^6.3.0
  google_sign_in_web: ^0.12.3
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.2
  fl_chart: ^0.70.2
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo.png"
  branding: "assets/images/logo.png"
  android_12:
    image: "assets/images/logo.png"
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

